[workspace]
members = [
  "apps/uzel/src-tauri",
  "apps/uzel-napd",
  "crates/napd",
  "crates/napd-protocol",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.89"
license = "MIT"

[workspace.dependencies]
napd = { path = "crates/napd" }
napd-protocol = { path = "crates/napd-protocol" }
tauri = { version = "=2.11.5" }
tauri-build = { version = "=2.6.3" }
